### ISSUE TITLE
The example in the README is outdated.

### ISSUE THREAD

**Issue by wroyca** [sshklifov/debug#1]
Thank for the plugin! I noticed that TermDebug has been renamed to PromptDebug, but the README example hasn't been updated to reflect this change. Here's an initial attempt I made, but since I'm not familiar with the plugin and the differences it introduces over the original TermDebug, I might have overlooked a few things here and there:

```vim
function! s:Debug(file)
  if PromptDebugIsOpen()
    echoerr 'Terminal debugger already running, cannot run two'
    return
  endif

  autocmd! User PromptDebugStopPre call s:DebugStopPre()
  autocmd! User PromptDebugRunPost call s:DebugRunPost()

  call PromptDebugStart()

  command! -nargs=0 Capture call PromptDebugGoToCapture()
  command! -nargs=0 Gdb call PromptDebugGoToGdb()
  command! -nargs=0 Pwd call PromptDebugShowPwd()
  command! -nargs=0 DebugSym call PromptDebugFindSym(expand('<cword>'))
  command! -nargs=? Break call PromptDebugGoToBreakpoint(<q-args>)
  command! -nargs=? Commands call PromptDebugEditCommands(<f-args>)

  nnoremap <silent> <leader>v <cmd>call PromptDebugEvaluate(expand('<cword>'))<CR>
  vnoremap <silent> <leader>v :<C-u>call PromptDebugEvaluate(<SID>GetRangeExpr())<CR>
  nnoremap <silent> <leader>br :call PromptDebugSendCommand("br " . <SID>GetDebugLoc())<CR>
  nnoremap <silent> <leader>tbr :call PromptDebugSendCommand("tbr " . <SID>GetDebugLoc())<CR>
  nnoremap <silent> <leader>unt :call PromptDebugSendCommands("tbr " . <SID>GetDebugLoc(), "c")<CR>
  nnoremap <silent> <leader>pc :call PromptDebugGoToPC()<CR>

  call PromptDebugSendCommand("set debug-file-directory /dev/null")
  call PromptDebugSendCommand("set print asm-demangle on")
  call PromptDebugSendCommand("set print pretty on")
  call PromptDebugSendCommand("set print frame-arguments none")
  call PromptDebugSendCommand("set print raw-frame-arguments off")
  call PromptDebugSendCommand("set print entry-values no")
  call PromptDebugSendCommand("set print inferior-events off")
  call PromptDebugSendCommand("set print thread-events off")
  call PromptDebugSendCommand("set print object on")
  call PromptDebugSendCommand("set breakpoint pending on")
  call PromptDebugSendCommand("skip -rfu ^std::")
  call PromptDebugSendCommand("skip -rfu ^cv::")

  let args = split(a:file, " ")
  call PromptDebugSendCommand("file " . args[0])
  if len(args) > 1
    call PromptDebugSendCommand("set args " . join(args[1:], " "))
  endif
  call PromptDebugSendCommand("start")
endfunction


function! s:GetDebugLoc()
  let basename = expand("%:t")
  let lnum = line(".")
  return printf("%s:%d", basename, lnum)
endfunction

function! s:DebugRunPost()
endfunction

function! s:DebugStopPre()
  silent! nunmap <leader>v
  silent! nunmap <leader>br
  silent! nunmap <leader>tbr
  silent! nunmap <leader>unt
  silent! nunmap <leader>pc

  silent! delcommand Capture
  silent! delcommand Gdb
  silent! delcommand Up
  silent! delcommand Pwd
  silent! delcommand Backtrace
  silent! delcommand Threads
  silent! delcommand DebugSym
  silent! delcommand Break
  silent! delcommand Commands
endfunction

function! ExeCompl(ArgLead, CmdLine, CursorPos)
  if a:CursorPos < len(a:CmdLine)
    return []
  endif
  let pat = "*" . a:ArgLead . "*"
  let cmd = ["find", ".", "(", "-path", "**/.git", "-prune", "-false", "-o", "-name", pat, ")"]
  let cmd += ["-type", "f", "-executable", "-printf", "%P\n"]
  return systemlist(cmd)
endfunction

command! -nargs=? -complete=customlist,ExeCompl Start call s:Debug(<q-args>)
```

**Comment by sshklifov** [comment]
Hi, thanks for checking out the plugin! I've added `:PromptDebugStart` which is a substitute for
`:Start` in the README. So the setup is simplified.

Regarding the differences between termdebug, there's a lot that has changed. Would adding a
list/video be useful? I stopped updating the README since I am the only active user :laughing:

**Comment by wroyca** [comment]
> Hi, thanks for checking out the plugin! I've added `:PromptDebugStart` which is a substitute for `:Start` in the README. So the setup is simplified.
> 
> Regarding the differences between termdebug, there's a lot that has changed. Would adding a list/video be useful? I stopped updating the README since I am the only active user 😆

Hello, 

> Regarding the differences between termdebug, there's a lot that has changed. Would adding a list/video be useful? I stopped updating the README since I am the only active user

For sure! 

If anything, I was initially confused on how to actually use your plugin - and a big part of that was I was completely unaware of termdebug, despite using neovim for years now; It took me a few tries to figure out that I had to packadd termdebug before attempting to use your plugin to begin with (by the way, quite neat! I wished for that kind of GDB bridge for a long time, not knowing it was right under my nose all this time)

I would personally recommend including the same example twice: once under Vimscript and once under Lua for Neovim users. Optionally adding more details about termdebug would also be neat for whoever is initially unaware of it (:

**Comment by sshklifov** [comment]
Just an fyi, you don't need to packadd termdebug. In fact, it is advised **not** to do so. They work independently. This plugin is an enhanced version of sorts.

**Comment by wroyca** [comment]
> Just an fyi, you don't need to packadd termdebug. In fact, it is advised **not** to do so. They work independently. This plugin is an enhanced version of sorts.

Uh really? TIL; will give it a try once I get home from work

**Comment by sshklifov** [comment]
I've updated the README, you can see what exactly has changed. In my mind, you only have to run `:PromptDebugStart`, so I haven't documented it in depth (nor are there any lua examples).

> Uh really? TIL; will give it a try once I get home from work

Please do, you are the second person to use the plugin. For me, it works flawlessly but I would like to make it usable for more people.

**Comment by wroyca** [comment]
> I've updated the README, you can see what exactly has changed. In my mind, you only have to run `:PromptDebugStart`, so I haven't documented it in depth (nor are there any lua examples).
> 
> > Uh really? TIL; will give it a try once I get home from work
> 
> Please do, you are the second person to use the plugin. For me, it works flawlessly but I would like to make it usable for more people.

Works well indeed, thank!

> I've updated the README, you can see what exactly has changed.

The changes are great! Definitely more comfortable to figure out how it works.

**Comment by wroyca** [comment]
The new README clears things up, so I'm closing this issue. :partying_face:
